CREATE TABLE archive_entity (
    id UUID PRIMARY KEY,
    slug VARCHAR(180) NOT NULL,
    entity_type VARCHAR(24) NOT NULL,
    project_type VARCHAR(32),
    event_type VARCHAR(32),
    title VARCHAR(300) NOT NULL,
    display_title VARCHAR(300),
    subtitle VARCHAR(500),
    short_description VARCHAR(1000),
    description TEXT,
    start_date DATE,
    end_date DATE,
    release_year INTEGER,
    visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    lifecycle_status VARCHAR(24) DEFAULT 'UNKNOWN',
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    hero_media_id UUID,
    wiki_title VARCHAR(300),
    wiki_url VARCHAR(1000),
    source VARCHAR(16) NOT NULL,
    source_page_id BIGINT,
    source_revision_id BIGINT,
    source_title VARCHAR(300),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_archive_entity_slug UNIQUE (slug),
    CONSTRAINT uk_archive_entity_wiki_page UNIQUE (source, source_page_id)
);

CREATE INDEX ix_archive_entity_public_show
    ON archive_entity (visibility, featured, sort_order, release_year);
CREATE INDEX ix_archive_entity_source_title
    ON archive_entity (source_title);

CREATE TABLE entity_property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE CASCADE,
    property_name VARCHAR(160) NOT NULL,
    normalized_name VARCHAR(160) NOT NULL,
    raw_value TEXT NOT NULL,
    normalized_value TEXT,
    ordinal INTEGER NOT NULL,
    source_revision_id BIGINT NOT NULL
);

CREATE INDEX ix_entity_property_entity ON entity_property (entity_id);
CREATE INDEX ix_entity_property_normalized ON entity_property (normalized_name);

CREATE TABLE entity_relationship (
    id UUID PRIMARY KEY,
    source_entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE CASCADE,
    target_entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE CASCADE,
    type VARCHAR(40) NOT NULL,
    label VARCHAR(240),
    start_date DATE,
    end_date DATE,
    strength INTEGER NOT NULL DEFAULT 50,
    visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    description TEXT,
    source_origin VARCHAR(32) NOT NULL,
    source_property VARCHAR(160),
    source_raw_value VARCHAR(1000),
    source_key VARCHAR(500),
    source_revision_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_relationship_source_key UNIQUE (source_origin, source_key),
    CONSTRAINT ck_relationship_strength CHECK (strength BETWEEN 1 AND 100),
    CONSTRAINT ck_relationship_not_self CHECK (source_entity_id <> target_entity_id)
);

CREATE INDEX ix_relationship_source ON entity_relationship (source_entity_id, visibility);
CREATE INDEX ix_relationship_target ON entity_relationship (target_entity_id, visibility);

CREATE TABLE tag (
    id UUID PRIMARY KEY,
    slug VARCHAR(180) NOT NULL UNIQUE,
    name VARCHAR(240) NOT NULL,
    source VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE entity_tag (
    entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE CASCADE,
    tag_id UUID NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
    PRIMARY KEY (entity_id, tag_id)
);

CREATE TABLE motif (
    id UUID PRIMARY KEY,
    slug VARCHAR(180) NOT NULL UNIQUE,
    title VARCHAR(240) NOT NULL,
    description TEXT,
    visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE entity_motif (
    entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE CASCADE,
    motif_id UUID NOT NULL REFERENCES motif(id) ON DELETE CASCADE,
    PRIMARY KEY (entity_id, motif_id)
);

CREATE TABLE media_asset (
    id UUID PRIMARY KEY,
    entity_id UUID REFERENCES archive_entity(id) ON DELETE SET NULL,
    type VARCHAR(20) NOT NULL,
    original_filename VARCHAR(500),
    storage_key VARCHAR(1000),
    external_url VARCHAR(1000),
    width INTEGER,
    height INTEGER,
    duration_ms BIGINT,
    alt_text VARCHAR(1000),
    caption VARCHAR(2000),
    copyright VARCHAR(500),
    visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    sort_order INTEGER NOT NULL DEFAULT 0,
    release_year INTEGER,
    media_variant VARCHAR(24) NOT NULL,
    mime_type VARCHAR(160),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE archive_entity
    ADD CONSTRAINT fk_archive_entity_hero_media
    FOREIGN KEY (hero_media_id) REFERENCES media_asset(id) ON DELETE SET NULL;

CREATE TABLE story (
    id UUID PRIMARY KEY,
    slug VARCHAR(180) NOT NULL UNIQUE,
    title VARCHAR(300) NOT NULL,
    teaser VARCHAR(1000),
    visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE story_step (
    id UUID PRIMARY KEY,
    story_id UUID NOT NULL REFERENCES story(id) ON DELETE CASCADE,
    entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE RESTRICT,
    sequence_number INTEGER NOT NULL,
    text TEXT,
    camera_focus VARCHAR(500),
    visualization_hint VARCHAR(500),
    CONSTRAINT uk_story_step_sequence UNIQUE (story_id, sequence_number)
);

CREATE TABLE import_run (
    id UUID PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL,
    filename VARCHAR(500),
    site_name VARCHAR(300),
    base_url VARCHAR(1000),
    generator VARCHAR(200),
    imported_pages INTEGER NOT NULL DEFAULT 0,
    updated_pages INTEGER NOT NULL DEFAULT 0,
    unchanged_pages INTEGER NOT NULL DEFAULT 0,
    skipped_pages INTEGER NOT NULL DEFAULT 0,
    relationships INTEGER NOT NULL DEFAULT 0,
    error_message TEXT
);

CREATE TABLE import_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_run_id UUID NOT NULL REFERENCES import_run(id) ON DELETE CASCADE,
    severity VARCHAR(16) NOT NULL,
    code VARCHAR(80) NOT NULL,
    page_title VARCHAR(300),
    property_name VARCHAR(160),
    raw_value VARCHAR(2000),
    message VARCHAR(2000) NOT NULL
);

CREATE INDEX ix_import_issue_run ON import_issue (import_run_id, severity);
