CREATE TABLE wiki_content_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id UUID NOT NULL REFERENCES archive_entity(id) ON DELETE CASCADE,
    heading VARCHAR(300) NOT NULL,
    normalized_heading VARCHAR(300) NOT NULL,
    heading_level INTEGER NOT NULL,
    body TEXT NOT NULL,
    ordinal INTEGER NOT NULL,
    source_revision_id BIGINT NOT NULL
);

CREATE INDEX ix_wiki_content_section_entity
    ON wiki_content_section (entity_id, ordinal);

CREATE INDEX ix_wiki_content_section_heading
    ON wiki_content_section (normalized_heading);
